close all;

inp_time = repmat([0.1 0.2]', [1 8]); %in seconds
inp_time(:, 7:end) = NaN;
inp_time(:, 3:end) = NaN;
%inp_time(:, 2:end) = NaN;

% [r_rec, r_rnd, t, opts] = SimWM_MultiRecRnd_new_att('SimTime', 1, 'RunningPlot', 1, ...
%     'RndRec_f', 0.25, 'InputTime', inp_time, 'N_rnd', 1024, ...
%     'RecToRndW_TargetFR', 0.3, 'RecToRndW_EIBalance', -1.015, ...
%     'RndToRecW_TargetFR', 0.2, 'RndToRecW_EIBalance', -1.015);
    
[r_rec, r_rnd, t, opts] = SimWM_MultiRecRnd_new_att('SimTime', 1, 'RunningPlot', 1, ...
    'RndRec_f', 0.25, 'InputTime', inp_time, 'N_rnd', 1024, ...
    'RecToRndW_TargetFR', 0.3, 'RecToRndW_EIBalance', -1.02, ...
    'RndToRecW_TargetFR', 0.2, 'RndToRecW_EIBalance', -1.02);

%% better with div norm?
close all;

inp_time = repmat([0.1 0.2]', [1 8]); %in seconds
inp_time(:, 7:end) = NaN;

[r_rec, r_rnd, t, opts] = SimWM_MultiRecRnd_new_att('SimTime', 1, 'RunningPlot', 1, ...
    'RndRec_f', 0.25, 'InputTime', inp_time, 'N_rnd', 1024, ...
    'UseDivNorm', 1, 'MaxAvgRecFR', 20, 'MaxAvgRndFR', 20, ...
    'RecToRndW_TargetFR', 0.3, 'RecToRndW_EIBalance', -1, ...
    'RndToRecW_TargetFR', 0.25, 'RndToRecW_EIBalance', -1);

%% better with div norm?
close all;

inp_time = repmat([0.1 0.2]', [1 8]); %in seconds
inp_time(:, 7:end) = NaN;

[r_rec, r_rnd, t, opts] = SimWM_MultiRecRnd_divnorm('SimTime', 1, 'RunningPlot', 1, ...
    'RndRec_f', 0.25, 'InputTime', inp_time, 'N_rnd', 1024, ...
    'RecToRndW_TargetFR', 0.3, 'RecToRndW_EIBalance', 0, ...
    'RndToRecW_TargetFR', 0.25, 'RndToRecW_EIBalance', 0);

%% test learning

inp_time = repmat([0.1 0.2]', [1 8]); %in seconds
inp_time(:, 7:end) = NaN;

[r_rec, r_rnd, t, opts] = SimWM_MultiRecRnd_new_att_learn('SimTime', 1, 'RunningPlot', 1, ...
    'RndRec_f', 0.3, 'InputTime', inp_time, 'N_rnd', 1024, ...
    'RecToRndW_TargetFR', 0.3, 'RecToRndW_EIBalance', -1.05, ...
    'RndToRecW_TargetFR', 0.2, 'RndToRecW_EIBalance', -1);